AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Sagemaker
Parameters:
  EndPointName:
    Description: "Endpoint for Email Spam Detection CloudFormation"
    Type: String

  S3BucketName:
    Description: "S3 bucket name"
    Type: String

Resources:
  S3BucketSpam:
    Type: AWS::S3::Bucket
    DependsOn: EmailLambdaFucntionName
    Properties:
      BucketName: !Ref S3BucketName
      AccessControl: PublicRead
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Function: !GetAtt [EmailLambdaFucntionName, Arn]
    DeletionPolicy: Retain
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "*"
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref S3BucketSpam
                - /*
      Bucket: !Ref S3BucketSpam
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt EmailLambdaFucntionName.Arn
      Action: "lambda:InvokeFunction"
      Principal: s3.amazonaws.com
      SourceAccount: !Ref "AWS::AccountId"
      SourceArn: !Sub "arn:aws:s3:::${S3BucketName}"
  LambdaRoleCF:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: LambdaRoleCF-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonSESFullAccess
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      Path: /
  EmailLambdaFucntionName:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: lambdacodeassign3
        S3Key: lambdaassign3.zip
      Description: lambda function for emailspam detection
      Environment:
        Variables:
          ENDPOINT_NAME: !Ref EndPointName
      FunctionName: spamemail_lambda_cloudformation
      Handler: lambda_function.lambda_handler
      MemorySize: 512
      Role:
        Fn::GetAtt:
          - LambdaRoleCF
          - Arn
      Runtime: python3.7
      Timeout: 60
  SesRuleSetSpam:
    Type: "AWS::SES::ReceiptRuleSet"
  SesRuleSpam:
    Type: "AWS::SES::ReceiptRule"
    DependsOn: S3BucketSpam
    Properties:
      Rule:
        Actions:
          - S3Action:
              BucketName: !Ref S3BucketName
        Enabled: true
        ScanEnabled: false
      RuleSetName: !Ref SesRuleSetSpam